<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <?php $helper = $this->helper('mpanel') ?>
    <?php $size = $helper->convertRatioToMinSize($this->getProductRatio()) ?>
    <?php $panelHelper = $this->helper('mpanel');
    $size = $panelHelper->convertRatioToMinSize();
    ?>
    <div class="block product-list-block new-list box-collateral">
		<div class="block-title sidebar-title-block">
			<h4>
				<?php if ($this->getTitle() != ''): ?>
					<span><?php echo $this->getTitle() ?></span>
				<?php else: ?>
					<span><?php echo $this->__('New Products') ?></span>
				<?php endif ?>
			</h4>
		</div>
        <div class="block-content">
            <?php
            $i = 0;
            foreach ($_products as $_product):
                ?>
        <?php $_product = Mage::getModel('catalog/product')->load($_product->getId()) ?>
                              <div class="product-content">
					<div class="product-top">
						<a class="product-image" href="<?php echo $_product->getProductUrl() ?>">
							<img alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" class="img-responsive">
						</a>
						<div class="controls">
							<div class="icon-links">
								<?php if ($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
									<button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" 
									onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-search"></em></button>
								<?php endif ?>
							</div>
						</div>
					</div>
					<div class="product-details">
						<h4 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>">							
						<?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name') ?>
							</a></h4>
						<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
						<?php echo $this->getPriceHtml($_product, true) ?>
					</div>
                </div>
    <?php endforeach ?>
        </div>
    </div>
    <?php else: ?>
    <div class="block product-list-block featured-list box-collateral">
		<div class="block-title sidebar-title-block">
			<h4>
				<?php if ($this->getTitle() != ''): ?>
					<span><?php echo $this->getTitle() ?></span>
				<?php else: ?>
					<span><?php echo $this->__('Featured Products') ?></span>
				<?php endif ?>
			</h4>
		</div>
        <div class="block-content">
            <div class="alert alert-danger no-product-display">
                <p><?php echo $this->__('There are no products matching the selection.') ?></p>
            </div>
        </div>
    </div>
<?php endif; ?>