<div class="blog-pages-categories">
<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<div class="row">
<div class="col-md-12 col-sm-12 col-xs-12">
<?php foreach ($posts as $post): ?>
    <div class="blog-view-container">
		<?php if ($post->getImage() != ''): ?>
			<div class="latest-post-img">
				<a href="<?php echo $post->getAddress(); ?>">
					<img class="img-responsive" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'blog/images/' . $post->getImage(); ?>"/>
				</a>
			</div>
		<?php endif ?>
        <div class="latest-post-decs">
			<div class="latest-date">
				<div class="icon-desc">
					<i class="fa fa-picture-o"></i>
				</div>
				<div class="day-desc">
					<span class="day"><?php echo date('d', strtotime($post->getCreatedTime())) ?></span>
					<span class="month"><?php echo date('M', strtotime($post->getCreatedTime())) ?></span>
				</div>
			</div>
			<div class="latest-decs">
				<h3><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h3>
				<div class="post-info">
					<i class="fa fa-user"></i>&nbsp;
					<?php if (!empty($postCats)): ?>
						<?php echo Mage::helper('blog')->__('Posted in'); ?>
						<?php foreach ($postCats as $title => $url): ?>
							<a href="<?php echo $url; ?>"><?php echo $title; ?></a>
						<?php endforeach; ?>
					<?php else: ?>
						<?php echo Mage::helper('blog')->__('Posted'); ?>
					<?php endif; ?><?php echo $this->__("by:"); ?> <?php echo $post->getUser(); ?>
					<?php echo $this->getTagsHtml($post) ?>
					<?php if ($this->getCommentsEnabled()): ?>
						<?php ($post->getCommentCount() >= 1) ? $post->getCommentCount() : 0 ?> <a class="comments" href="<?php echo $post->getAddress(); ?>#commentBox" ><i class="fa fa-comments-o"></i>&nbsp;<?php echo Mage::helper('blog')->__(' Comments'); ?></a>
					<?php endif; ?>
				</div>
			</div>
        </div>
        <div class="postContent">
			<?php echo $post->getPostContent(); ?>
		</div>
        <?php echo $this->getBookmarkHtml($post) ?>
        <div class="tags"></div>
    </div>
<?php endforeach; ?>
</div>
</div>
<div class="toolbar-bottom">
<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
</div>
</div>