<div class="blog-pages-categories">
<?php $post = $this->getPost(); ?>
<div class="row">
	<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
</div>
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="blog-view-container">
			<?php if ($post->getImage() != ''): ?>
				<div class="latest-post-img">
					<a href="<?php echo $post->getAddress(); ?>">
						<img class="img-responsive" alt="" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'blog/images/' . $post->getImage(); ?>"/>
					</a>
				</div>
			<?php endif ?>
			<div class="latest-post-decs">
				<div class="latest-date">
					<div class="icon-desc">
						<i class="fa fa-picture-o"></i>
					</div>
					<div class="day-desc">
						<span class="day"><?php echo date('d', strtotime($post->getCreatedTime())) ?></span>
						<span class="month"><?php echo date('M', strtotime($post->getCreatedTime())) ?></span>
					</div>
				</div>
				<div class="latest-decs">
					<h3><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h3>
					<div class="post-info">
						<i class="fa fa-user"></i>&nbsp;
						<?php if (!empty($postCats)): ?>
							<?php echo Mage::helper('blog')->__('Posted in'); ?>
							<?php foreach ($postCats as $title => $url): ?>
								<a href="<?php echo $url; ?>"><?php echo $title; ?></a>
							<?php endforeach; ?>
						<?php else: ?>
							<?php echo Mage::helper('blog')->__('Posted'); ?>
						<?php endif; ?><?php echo $this->__("by:"); ?> <?php echo $post->getUser(); ?>
						<?php echo $this->getTagsHtml($post) ?>
					</div>
				</div>
			</div>

			<div class="postContent"><?php echo $post->getPostContent(); ?></div>
			<?php echo $this->getBookmarkHtml($post) ?>
			<!-- Share -->
			<?php if(Mage::getStoreConfig('mpanel/share_this/blog_detail')): ?>
			<div class="share-blog">
				<div class="social-icons social-share-mg">
					 <?php echo Mage::getStoreConfig('mpanel/share_this/span_tags') ?>
				</div>
			</div>
			<?php endif; ?>
		</div>

		<!-- Comment Section -->

		<?php if ($this->getCommentsEnabled()): ?>
			<?php $comments = $this->getComment(); ?>
			<div class="postTitle"><a name="commentBox" ></a>
				<h2><?php echo $this->__('Post Comments') ?></h2>
			</div>
				<?php foreach ($comments as $comment) : ?>
					<div class="commentWrapper">
						<div class="commentDetails"><h4 class="username"><?php echo $comment->getUser(); ?></h4> 
							<p><?php echo $this->formatDate($comment->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?></p>
						</div>
						<div class="commentContent"><?php echo nl2br($comment->getComment()); ?></div>
					</div>
				<?php endforeach; ?>
				<div class="row">
					<div class="col-md-12 col-sm-12 col-xs-12 toolbar-bottom-blog">
						<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
					</div>
				</div>
			<?php if ($post->getComments()): ?>
				<div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
			<?php else: ?>
				<div class="comment-forms">
				<?php if ($this->getLoginRequired()): ?>
					<?php if ($this->helper('customer')->isLoggedIn()): ?>
						<form action="" id="postComment" method="post">
							<fieldset class="group-select">
							<div class="postTitle">
								<h2><?php echo Mage::helper('blog')->__('Submit Comment') ?></h2>
							</div>
								<ul class="form-list">
									<li>
										<div class="input-box aw-blog-comment-area form-group">
											<label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
											<textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" style="height:150px;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
										</div>
									</li>
								</ul>
							</fieldset>
							<div class="button-set text-center">
								<input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
								<input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
								<input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
								<button class="btn btn-sm btn-primary form-button" type="submit"><span><span><?php echo Mage::helper('blog')->__('SUBMIT') ?></span></span></button>
							</div>
						</form>

						<script type="text/javascript">
							var contactForm = new VarienForm('postComment', false);
						</script>

					<?php else: ?>
					<div class="text-center alert alert-warning">
						<p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
						<p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
					</div>
					<?php endif ?>

				<?php else: ?>
					
					<form action="" id="postComment" method="post">
						<fieldset class="group-select">
							<div class="postTitle">
								<h2><?php echo Mage::helper('blog')->__('Submit Comment') ?></h2>
							</div>
							<ul class="form-list">
								<li>
									<div class="row">
										<div class="input-box col-md-6 col-sm-6 col-xs-12 form-group">
											<input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" placeholder="<?php echo $this->__('Name') ?>*" title="<?php echo $this->__('Name') ?>" class="required-entry input-text" type="text" />
										</div>
										<div class="input-box col-md-6 col-sm-6 col-xs-12 form-group">
											<input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" placeholder="<?php echo $this->__('Email') ?>*" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email" type="text" />
										</div>
									</div>
									<div class="row">
										<div class="input-box aw-blog-comment-area col-md-12 col-sm-12 col-xs-12 form-group">
											<textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>"  placeholder="<?php echo $this->__('Comment') ?>*" class="required-entry input-text" style="height:150px;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
										</div>
									</div>
								</li>

								<?php
								if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()) {
									?><li><?php
						require_once 'recaptcha/recaptchalib-aw.php';

						// Get a key from http://recaptcha.net/api/getkey
						$publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
						$privatekey = Mage::getStoreConfig('blog/recaptcha/privatekey');
						$error = null;

						echo recaptcha_get_html($publickey, $error);
									?></li><?php
					}
								?>
							</ul>
						</fieldset>
						<div class="button-set text-center">
							<input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
							<button class="btn btn-sm btn-primary form-button" type="submit"><span><span><?php echo Mage::helper('blog')->__('SUBMIT') ?></span></span></button>
						</div>
					</form>

					<script type="text/javascript">
						var contactForm = new VarienForm('postComment', false);
					</script>
				<?php endif; ?>
			</div>
			<?php endif; ?>
		<?php endif; ?>
		</div>
	</div>
</div>