<?php $helper = $this->helper('mpanel') ?>
<?php $size = $helper->convertRatioToSize($this->getProductRatio()) ?>
<?php if (Mage::getStoreConfig('deals/general/enabled')): ?>
    <?php
    $layout = Mage::getSingleton('core/layout');
    $productCollection = $this->getProductCollection();
    $toolbar = $this->getToolbarBlock();
    $pager = $layout->createBlock('page/html_pager');
    $toolbar->setChild('product_list_toolbar_pager', $pager);
    $toolbar->setCollection($productCollection);
    
    $toolbar->setMode($this->getMode());
	$toolbar->setTemplate('mgs/deals/toolbar.phtml');
    ?> 
	<div class="top-deals-toolbar">
		<?php echo $toolbar->toHtml(); ?>
	</div>
    <?php if (count($productCollection) > 0): ?>
	<div class="category-products">
        <?php if ($this->getMode() != 'grid'): ?>
            <ul class="deals-container products-list">
                <?php foreach ($productCollection as $product): ?>
                    <?php $_product = Mage::getModel('catalog/product')->load($product->getId()) ?>
                    <li class="item">
						<div class="row">
							<div class="col-md-3 col-sm-6 col-xs-12">
								<div class="product-image-container">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
									<div class="discount-save">
										<div class="save-content">
											<?php echo $this->__('Save') ?>
											<div class="percent">
												<?php $save = $_product->getPrice() - $_product->getFinalPrice() ?>
												<?php $percent = round(($save * 100) / $_product->getPrice(), 1) ?>
												<?php echo $percent ?>%
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="col-md-6 col-sm-6 col-xs-12">
								<div class="product-desc">
									<h2><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"><?php echo $_product->getName() ?></a></h2>
									<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
									<div class="product-price">
										<?php echo $this->getPriceHtml($_product, true) ?>
									</div>
									<div class="product-deals-desc">
										<?php echo Mage::helper('core/string')->truncate($_product->getDescription(), 220); ?>
										<p class="view-detail"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View details') ?></a></p>
									</div>
								</div>
							</div>
							<div class="col-md-3 col-sm-6 col-xs-12">
								<div class="deals-info">
									<div class="row">
										<div class="col-xs-12">
											<?php echo $this->getLayout()->createBlock('deals/deals')->setTemplate('mgs/deals/list.phtml')->setProductId($_product->getId())->toHtml(); ?>
										</div>
									</div>
									<div class="deals-sold">
										<?php echo $this->__('Sold:') ?> <span><?php echo $this->getSold($_product->getId()) ?></span>
									</div>
									<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId(); ?>">
										<input name="qty" type="text" class="input-text qty addcart-qty" id="addcartqty" maxlength="12" value="<?php echo $this->getMinimalQty($_product) ?>" />
										<button class="button-addcart btn btn-sm btn-primary" onclick="productAddToCartForm_<?php echo $_product->getId(); ?>.submit();"><span><?php echo $this->__('Buy Now') ?></span></button>
									</form>
									<script type="text/javascript">
											var productAddToCartForm_<?php echo $_product->getId(); ?> = new VarienForm('product_addtocart_form_<?php echo $_product->getId(); ?>');
											productAddToCartForm_<?php echo $_product->getId(); ?>.submit = function() {
												if (this.validator.validate()) {
													this.form.submit();
												}
											}.bind(productAddToCartForm_<?php echo $_product->getId(); ?>);
									</script>
								</div>
							</div>				
						</div>
                    </li>
                <?php endforeach ?>
            </ul>
        <?php else: ?>
		<div class="products-grid row-3">
            <?php $_collectionSize = $productCollection->count() ?>
            <?php $_columnCount = $this->getColumnCount(); ?>
            <?php
            $i = 0;
            foreach ($productCollection as $product):
                $_product = Mage::getModel('catalog/product')->load($product->getId());
				$i++;
                ?>
				<?php $class = $helper->getItemClass(3, $i) ?>
                    <div class="col-md-4 col-sm-6 col-xs-12 item <?php if ($i % 3 == 1): ?>first-row-item <?php endif; ?><?php echo $class ?>">
                        <div class="product-content">
							<div class="product-top">
								<div class="row">
									<div class="col-md-12">
										<?php echo $this->getLayout()->createBlock('deals/deals')->setTemplate('mgs/deals/list.phtml')->setProductId($_product->getId())->toHtml(); ?>
									</div>
								</div>
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
								<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>" class="product-image"><img class="img-responsive img-two" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height'])?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
							
								<div class="controls">
									<div class="add-to-cart">
										<?php if ($_product->isSaleable()): ?>
											<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-xs btn-default btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>');"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
										<?php endif; ?>
									</div>
									<ul class="icon-links pull-right">
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><button type="button" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>"><em class="fa fa-heart-o"></em></button></li>
										<?php endif; ?>
										<?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
											<li><button  type="button" onclick="setLocation('<?php echo $_compareUrl ?>')" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare"><em class="fa fa-retweet"></em></button></li>
										<?php endif; ?>
									</ul>
								</div>
							</div>
							<div class="product-desc">
								<h4 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName(); ?></a></h4>
								<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
								<?php echo $this->getPriceHtml($_product, true) ?>
							</div>
						</div>
                    </div>
            <?php endforeach ?>
			</div>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last']);</script>
        <?php endif; ?>
    <?php endif; ?>
	</div>
	<div class="bottom-toolbar">
		<?php echo $toolbar->toHtml();?>
	</div>
	
<?php endif; ?>