<?php 
	$categories = $this->getCategoryCollection();
	$panelHelper = $this->helper('mpanel');
	$size = $panelHelper->convertRatioToSize($this->getProductRatio());
	if($this->getColumn()){
		$col = $this->getColumn();
	}
	else{
		$col = 3;
	}
	
	$col = $panelHelper->convertColRow($col);
?>
<?php if(Mage::getStoreConfig('mpanel/catalog/featured')!=''): ?>
	<?php if(count($categories)>0): ?>
		<div class="featured-category-products featured-category-products-tabs category-tabs">
			<?php if($this->getTitle()!=''): ?>
				<div class="carousel_wrapper title-categories">
					<div class="title">
						<h2><?php echo $this->getTitle() ?></h2>
					</div>
				</div>
			<?php endif ?>
			<div class="category-product-item">
				<div class="col-md-12">
					<div class="row">
						<div class="tabs-container">
							<?php $i = 0; foreach ($categories as $_category): $i++; ?>
								<?php if($i == 1): ?><?php $idfirst =  $_category->getId();?><?php endif ?>
							<?php endforeach ?>
							<ul id="category-product-tabs-<?php echo $idfirst ?>" class="nav nav-tabs tab-menu tab-products" role="tablist">
								<?php $i=0; foreach($categories as $_category): $i++; ?>										
									<li class="section-tab3-<?php echo $i ?> <?php if ($i == 1): ?> active<?php endif ?>" role="presentation">
										<a href="#section-tab3-<?php echo $_category->getId(); ?>" role="tab" data-toggle="tab" aria-expanded="true" >
											<span><?php echo $_category->getName() ?></span>
										</a>
									</li>
								<?php endforeach ?>
								<?php $totalca = $i; ?>
							</ul>
							<script type="text/javascript">
								if(mgsjQuery(window).width() < 768) {
									initSliderTestimonials('category-product-tabs-<?php echo $idfirst ?>', 1,false,false,true,false);
									var flagca = 1;
									mgsjQuery('#category-product-tabs-<?php echo $idfirst ?> .owl-controls .owl-next').click(function(){
										if(flagca < <?php echo $totalca ?>){
											flagca++;
											tabchange();
										}else{
											flagca = 1;
											tabchange();
										}
									});
									mgsjQuery('#category-product-tabs-<?php echo $idfirst ?> .owl-controls .owl-prev').click(function(){
										if(flagca == 1){
											flagca = <?php echo $totalca ?>;
											tabchange();
										}else{
											flagca--;
											tabchange();
										}
									});
									function tabchange(){
										mgsjQuery('#content-category-tab-<?php echo $idfirst ?> > .tab-pane').removeClass('active');
										mgsjQuery('#category-product-tabs-<?php echo $idfirst ?> li').removeClass('active');
										mgsjQuery('#content-category-tab-<?php echo $idfirst ?> .section-tab3-'+flagca).addClass('active');
										mgsjQuery('#category-product-tabs-<?php echo $idfirst ?> .section-tab3-'+flagca).addClass('active');
									}
								}
							</script>
							<div class="products tab-content"  id="content-category-tab-<?php echo $idfirst ?>">
										<?php $i=0; foreach($categories as $_category): $i++; ?>
											<?php $products = $this->getProductByCategory($_category) ?>
											<?php if(count($products)>0): ?>
												 <div class="tab-pane<?php if ($i == 1): ?> active<?php endif ?> section-tab3-<?php echo $i; ?>" id="section-tab3-<?php echo $_category->getId(); ?>" role="tabpanel">
													<ul class="products-grid row" >
													<?php foreach($products as $_product): ?>
														<?php //$_product = Mage::getModel('catalog/product')->load($_product) ?>
														<li class="item col-md-<?php echo $col ?> col-sm-<?php echo $col ?> col-xs-12">
															<div class="product-content">
                                                                <div class="product-top">
																	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
																		<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" 
																		alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>		
																		<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-two"/>
																	</a>
																	<?php echo $panelHelper->getProductLabel($_product) ?>
																	<div class="controls">
																		<div class="add-to-cart">
																			<?php if ($_product->isSaleable()): ?>
																				<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart btn-default btn-xs" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart'); ?></button>
																			<?php endif; ?>
																		</div>
																		<ul class="icon-links pull-right">									
																			<?php if ($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
																				<li class="li-quickview">
																					<button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" 
																					onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-search"></em></button>
																				</li>
																			<?php endif ?>
																			<?php if ($this->helper('wishlist')->isAllow()) : ?>
																				<li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="fa fa-heart-o"></em></button></li>
																			<?php endif; ?>
																			<?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
																				<li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-retweet"></em></button></li>
																			<?php endif; ?>
																		</ul>
																	</div>
																</div>
																<div class="product-desc">
																	<h4 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->stripTags($_product->getName(), null, true) ?></a></h4>
																	<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
																	<?php echo $this->getLayout()->createBlock('review/helper')->getSummaryHtml($_product, 'short');?>
																</div>

                                                            </div>
														</li>
													<?php endforeach ?>
												</ul>
												</div>
											<?php endif ?>
										<?php endforeach ?>
							</div>
						</div>
					</div>
				</div>
			</div>
			
		</div>
	<?php endif ?>
<?php else: ?>
	<div class="alert alert-danger"><?php echo $this->__('Please set "Featured Product Attribute"') ?></div>
<?php endif ?>
