<?php 
	$categories = $this->getCategoryCollection();
	$panelHelper = $this->helper('mpanel');
	$size = $panelHelper->convertRatioToSize($this->getProductRatio());
	if($this->getColumn()){
		$col = $this->getColumn();
	}
	else{
		$col = 3;
	}
	
	$col = $panelHelper->convertColRow($col);
?>
<?php if(Mage::getStoreConfig('mpanel/catalog/featured')!=''): ?>
	<?php if(count($categories)>0): ?>
		<div class="featured-category-products featured-category-products-tabs">
			<?php if($this->getTitle()!=''): ?>
				<div class="carousel_wrapper">
					<div class="title">
						<h2><?php echo $this->getTitle() ?></h2>
					</div>
				</div>
			<?php endif ?>
			<div class="category-product-item">
				<div class="col-md-12">
					<div class="row">
						<div class="tabs-container">
							<?php $i = 0; foreach ($categories as $_category): $i++; ?>
								<?php if($i == 1): ?><?php $idfirst =  $_category->getId();?><?php endif ?>
							<?php endforeach ?>
							<ul id="tab-on-tab-<?php echo $idfirst ?>" class="nav nav-tabs tab-menu tab-products" role="tablist">
								<?php $i=0; foreach($categories as $_category): $i++; ?>										
									<li  class="sections-flip-<?php echo $i ?><?php if($i==1): ?> active<?php endif ?>" role="presentation">
										<a href="#sections-flip-<?php echo $_category->getId(); ?>" role="tab" data-toggle="tab" aria-expanded="true" >
											<span><?php echo $_category->getName() ?></span>
										</a>
									</li>
								<?php endforeach ?>
								<?php $total = $i ?>
							</ul>
							<script type="text/javascript">
								if(mgsjQuery(window).width() < 768) {
									initSliderTestimonials('tab-on-tab-<?php echo $idfirst ?>', 1,false,false,true,false);
									var flagtot = 1;
									mgsjQuery('#tab-on-tab-<?php echo $idfirst ?> .owl-controls .owl-next').click(function(){
										if(flagtot < <?php echo $total ?>){
											flagtot++;
											tabOnTabChange();
										}else{
											flagtot = 1;
											tabOnTabChange();
										}
									});
									mgsjQuery('#tab-on-tab-<?php echo $idfirst ?> .owl-controls .owl-prev').click(function(){
										if(flagtot == 1){
											flagtot = <?php echo $total ?>;
											tabOnTabChange();
										}else{
											flagtot--;
											tabOnTabChange();
										}
									});
									function tabOnTabChange(){
										mgsjQuery('#content-tabfull-slider-<?php echo $idfirst ?> > .tab-pane').removeClass('active');
										mgsjQuery('#tabs-full-slider-<?php echo $idfirst ?> li').removeClass('active');
										mgsjQuery('#content-tabfull-slider-<?php echo $idfirst ?> .section-tab2-'+flagfull).addClass('active');
										mgsjQuery('#tabs-full-slider-<?php echo $idfirst ?> .section-tab2-'+flagfull).addClass('active');
									}
								}
							</script>
							<div id="content-on-tab-<?php echo $idfirst ?>" class="products tab-content text-left">
								<?php $i=0; foreach($categories as $_category): $i++; ?>
									<?php $products = $this->getProductByCategory($_category) ?>
									<?php if(count($products)>0): ?>
									<div class="tab-pane<?php if($i==1): ?> active<?php endif ?> <?php echo "sections-flip-".$i ?>" id="sections-flip-<?php echo $_category->getId(); ?>" role="tabpanel">
										<div class="row">
											<div class="tab-content  product-inner-tabs">
												<?php $b=0; foreach($products as $_product): $b++ ?>
													<div role="tabpanel" class="tab-pane <?php if($b == 1): ?>active<?php endif ?>" id="product-intabs-<?php echo $_product->getId(); ?>">
														<div class="col-md-4 col-sm-4 col-xs-12 product-img">
															<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
																<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>"
																alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
																<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($size['width'], $size['height']) ?>"
																alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-two"/>
															</a>
														</div>
														<div class="col-md-8 col-sm-8 col-xs-12 product-desc">
															<div class="row">
																<div class="col-md-9  col-sm-9 col-xs-12">
																	<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->stripTags($_product->getName(), null, true) ?></a></h2>
																</div>
																<div class="col-md-3 col-sm-3 col-xs-12 text-right">
																	<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
																</div>
															</div>
															<?php echo $this->getLayout()->createBlock('review/helper')->getSummaryHtml($_product, 'short');?>
															<p class="color-gray"><?php echo $_product->getShortDescription(); ?></p>
															<div class="controls-list">
																<ul class="icon-links">
																	<?php if ($_product->isSaleable()): ?>
																		<li><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></button></li>
																	<?php endif; ?>
																	<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
																		<li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-search"></em></button></li>
																	<?php endif ?>
																	<?php if ($this->helper('wishlist')->isAllow()) : ?>
																		<li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="fa fa-heart-o"></em></button></li>
																	<?php endif; ?>
																	<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
																		<li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-retweet"></em></button></li>
																	<?php endif; ?>
																</ul>
															</div>
														</div>
													</div>
												<?php endforeach ?>
											</div>
											<div class="col-md-8 col-sm-12 col-xs-12 tabs-img tab-pane<?php if($i==1): ?> active<?php endif ?>" role="tabpanel">
												<div class="row">
													<div class="nav nav-tabs" role="tablist" id="inner_tabs_<?php echo $_category->getId() ?>">
														<?php $a=0; foreach($products as $_product): $a++ ?>
															<div class="inner-menu-tabs <?php if($a == 1): ?>active<?php endif ?>" role="presentation">
																<a href="#product-intabs-<?php echo $_product->getId(); ?>" role="tab" data-toggle="tab">
																	<img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(300, 300) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
																</a>
															</div>
														<?php endforeach ?>
														<script type="text/javascript">
															initSliderThumbnail('inner_tabs_<?php echo $_category->getId() ?>', <?php echo $this->getColumn() ?>,false,false,true,false);
														</script>
													</div>
												</div>
											</div>
										</div>
									</div>
									<?php endif ?>
								<?php endforeach ?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	<?php endif ?>
<?php else: ?>
	<div class="alert alert-danger"><?php echo $this->__('Please set "Featured Product Attribute"') ?></div>
<?php endif ?>
