<?php 
	$categories = $this->getCategoryCollection();
	$panelHelper = $this->helper('mpanel');
	$size = $panelHelper->convertRatioToSize($this->getProductRatio());
	if($this->getColumn()){
		$col = $this->getColumn();
	}
	else{
		$col = 3;
	}
	
	$col = $panelHelper->convertColRow($col);
?>
<?php if(Mage::getStoreConfig('mpanel/catalog/featured')!=''): ?>
	<?php if(count($categories)>0): ?>
		<div class="categories-product-slider-2row">
			<?php if($this->getTitle()!=''): ?>
				<div class="carousel_wrapper">
					<div class="title">
						<h2><?php echo $this->getTitle() ?></h2>
					</div>
				</div>
			<?php endif ?>
			<div class="category-product-item">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="row">
						<div class="tabs-container">
							<?php $i = 0; foreach ($categories as $_category): $i++; ?>
								<?php if($i == 1): ?><?php $idfirst =  $_category->getId();?><?php endif ?>
							<?php endforeach ?>
							<ul id="tab-2rows-<?php echo $idfirst ?>" class="nav nav-tabs tab-menu tab-products" role="tablist">
								<?php $i=0; foreach($categories as $_category): $i++; ?>										
									<li class="section-tab4-<?php echo $i ?> <?php if ($i == 1): ?> active<?php endif ?>" role="presentation">
										<a href="#section-tab4-<?php echo $_category->getId(); ?>" role="tab" data-toggle="tab" aria-expanded="true" >
											<span><?php echo $_category->getName() ?></span>
										</a>
									</li>
								<?php endforeach ?>
								<?php $totaltwo = $i; ?>
							</ul>
							<script type="text/javascript">
								if(mgsjQuery(window).width() < 768) {
									initSliderTestimonials('tab-2rows-<?php echo $idfirst ?>', 1,false,false,true,false);
									var flagtwo = 1;
									mgsjQuery('#tab-2rows-<?php echo $idfirst ?> .owl-controls .owl-next').click(function(){
										if(flagtwo < <?php echo $totaltwo ?>){
											flagtwo++;
											tabTwoRowChange();
										}else{
											flagtwo = 1;
											tabTwoRowChange();
										}
									});
									mgsjQuery('#tab-2rows-<?php echo $idfirst ?> .owl-controls .owl-prev').click(function(){
										if(flagtwo == 1){
											flagtwo = <?php echo $totaltwo ?>;
											tabTwoRowChange();
										}else{
											flagtwo--;
											tabTwoRowChange();
										}
									});
									function tabTwoRowChange(){
										mgsjQuery('#content-tab-2rows-<?php echo $idfirst ?> > .tab-pane').removeClass('active');
										mgsjQuery('#tab-2rows-<?php echo $idfirst ?> li').removeClass('active');
										mgsjQuery('#content-tab-2rows-<?php echo $idfirst ?> .section-tab4-'+flagtwo).addClass('active');
										mgsjQuery('#tab-2rows-<?php echo $idfirst ?> .section-tab4-'+flagtwo).addClass('active');
									}
								}
							</script>
							<div class="products tab-content"  id="content-tab-2rows-<?php echo $idfirst ?>">
                                <?php $i = 0;
                                foreach ($categories as $_category): $i++; ?>
                                    <?php $products = $this->getProductByCategory($_category) ?>
            <?php if (count($products) > 0): ?>
                                        <div class="tab-pane<?php if ($i == 1): ?> active<?php endif ?> section-tab4-<?php echo $i; ?>" id="section-tab4-<?php echo $_category->getId(); ?>" role="tabpanel">
                                            <div class="products-grid row">
                                                <ul class="owl-carousel products-carousel" id="category_products_slider_<?php echo $_category->getId(); ?>" >
                                                    <?php $k=0; foreach($products as $_product): $k++; ?>
                    <?php $_product = Mage::getModel('catalog/product')->load($_product->getId());  ?>
                                                        <?php if($k % 2 == 1): ?><li class="item"><?php endif ?>
                                                            <div class="product-content">
                                                                <div class="product-top">
																	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
																		<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" 
																		alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>		
																		<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-two"/>
																	</a>
																	<?php echo $panelHelper->getProductLabel($_product) ?>
																	<div class="controls">
																		<div class="add-to-cart">
																			<?php if ($_product->isSaleable()): ?>
																				<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart btn-default btn-xs" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart'); ?></button>
																			<?php endif; ?>
																		</div>
																		<ul class="icon-links pull-right">									
																			<?php if ($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
																				<li class="li-quickview">
																					<button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" 
																					onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-search"></em></button>
																				</li>
																			<?php endif ?>
																			<?php if ($this->helper('wishlist')->isAllow()) : ?>
																				<li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="fa fa-heart-o"></em></button></li>
																			<?php endif; ?>
																			<?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
																				<li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-retweet"></em></button></li>
																			<?php endif; ?>
																		</ul>
																	</div>
																</div>
																<div class="product-desc">
																	<h4 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->stripTags($_product->getName(), null, true) ?></a></h4>
																	<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
																	<?php echo $this->getLayout()->createBlock('review/helper')->getSummaryHtml($_product, 'short');?>
																</div>

                                                            </div>
                                                        <?php if($k % 2 == 0): ?></li><?php endif ?>
                <?php endforeach ?>
                                                </ul>
                                            </div>
                                        </div>

                                        <script type="text/javascript">
                                            initSlider('category_products_slider_<?php echo $_category->getId() ?>', <?php echo $this->getColumn() ?>, false, false, true, false);
                                        </script>
                                    <?php endif ?>

        <?php endforeach ?>
                            </div>
						</div>
					</div>
				</div>
			</div>
			
		</div>
		
	<?php endif ?>
<?php else: ?>
	<div class="alert alert-danger"><?php echo $this->__('Please set "Featured Product Attribute"') ?></div>
<?php endif ?>
