<?php if (!Mage::registry('current_category')) return ?>
<?php $_categories = $this->getCurrentChildCategories() ?>
<?php $_count = is_array($_categories)?count($_categories):$_categories->count(); ?>
<?php if($_count): ?>
<div class="row">
	<div class="collection-lookbook text-colour-white link-colour-white">
		<?php foreach ($_categories as $_category): ?>
			<?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
			<?php if($_category->getIsActive()): ?>
			<div class="lookbook-content">
				<div class="landing-img">
					<?php if($_category->getThumbnail()!=''): ?>
						<a href="<?php echo $this->getCategoryUrl($_category) ?>">
							<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>catalog/category/<?php echo $_category->getThumbnail() ?>" alt="<?php echo $this->escapeHtml($_category->getName()) ?>" class="img-responsive"/>
						</a>
					<?php endif ?>
				</div>
				<div class="text-lookbook">
					<h2><a class="grid-name" href="<?php echo $this->getCategoryUrl($_category) ?>"><?php echo $this->escapeHtml($_category->getName()) ?></a></h2>
					<h5><?php echo $_category->getDescription(); ?><!--span class="category-product-count">(<?php echo $this->__('%s products',$_category->getProductCount()) ?>)</span--></h5>
					<div class="view-more">
						<a href="<?php echo $this->getCategoryUrl($_category) ?>" class="a-default">Shop Now</a>
					</div>
				</div>
			</div>
			<?php endif; ?>
		<?php endforeach ?>
	</div>
</div>
<?php endif; ?>