<?php
/* * ****************************************************
 * Package   : Brand
 * Author    : HIEPNH
 * Copyright : (c) 2015
 * ***************************************************** */
?>
<?php
$collection = $this->getBrandCollection();
$featuredCollection = $this->getFeaturedBrandCollection();
$params = $this->getRequest()->getParams();
$urlKey = $this->getUrlKey();
$query = '';
foreach ($params as $key => $value) {
    if ($key != 'order' && $key != 'dir') {
        $query .= $key . '=' . $value;
    }
}
$helper = Mage::helper('brand');
if ($helper->iconWidth() != '') {
    $iconWidth = $helper->iconWidth();
} else {
    $iconWidth = 135;
}
if ($helper->iconHeight() != '') {
    $iconHeight = $helper->iconHeight();
} else {
    $iconHeight = 135;
}
?>
<?php $panelHelper = $this->helper('mpanel') ?>

<?php if ($this->getDescription() != ''): ?>
    <div class="brand-description std">
        <?php echo $this->getDescription(); ?>
    </div>
<?php endif; ?>
<?php if (count($featuredCollection)): ?>
    <div class="featured-brand-container">
        <div class="feature-brand-title page-title">
            <h2><?php echo $this->__('Featured Brands'); ?></h2>
        </div>
        <ul class="feature-brands row-4">
			<?php $i= 0; ?>
            <?php foreach ($featuredCollection as $brand): ?>
				<?php $i++ ?>
                <li class="feature-brand-item col-md-3 col-sm-4 col-xs-6 <?php if ($i % 4 == 1): ?>first-row-item <?php endif; ?> <?php if ($i % 2 == 1): ?>row-2-first<?php endif; ?> <?php if ($i % 3 == 1): ?>row-3sm-first<?php endif; ?>">
                    <div class="feature-brand-image">
                        <a title="<?php echo $brand->getTitle(); ?>"
                           href="<?php echo $this->getUrl() . $urlKey . '/' . $brand->getUrlKey(); ?>">
                               <?php if ($brand->getIcon() != ''): ?>
                                <img style="width: <?php echo $iconWidth ?>px;" class="brand-img img-responsive"
                                     alt="<?php echo $brand->getTitle(); ?>"
                                     src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'media/' . $brand->getIcon(); ?>">
                                 <?php else: ?>
                                <img style="width: <?php echo $iconWidth ?>px;" class="brand-img img-responsive"
                                     alt="<?php echo $brand->getTitle(); ?>"
                                     src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'media/mgs/brand/no_image.jpg'; ?>">
                                 <?php endif; ?>
                        </a>
                    </div>
                    <h3 class="feature-brand-title">
                        <a title="<?php echo $brand->getTitle(); ?>"
                           href="<?php echo $this->getUrl() . $urlKey . '/' . $brand->getUrlKey(); ?>"><?php echo $brand->getTitle(); ?>
                            <span><?php echo $this->__('(%s)', $this->getProductCount($brand->getId())); ?></span></a>
                    </h3>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
<div class="brands-container">
    <?php echo $this->getChildHtml('brand.search'); ?>
    <?php if (count($collection)): ?>
        <div class="brands-toolbar toolbar">
            <div class="sorter pager">
                <div class="sort-by">
                    <label>Sort By</label>
                    <?php if ($query != ''): ?>
                        <?php if (!isset($params['dir'])): ?>
                            <select onchange="setLocation(this.value)">
                                <option
                                    <?php if (isset($params['order']) && $params['order'] == 'priority'): ?>selected="selected"<?php endif; ?>
                                    value="<?php echo $this->getUrl() . $urlKey . '?' . $query . '&dir=asc' . '&order=priority'; ?>">
                                        <?php echo $this->__('Priority'); ?>
                                </option>
                                <option
                                    <?php if (isset($params['order']) && $params['order'] == 'title'): ?>selected="selected"<?php endif; ?>
                                    value="<?php echo $this->getUrl() . $urlKey . '?' . $query . '&dir=asc' . '&order=title'; ?>">
                                        <?php echo $this->__('Title'); ?>
                                </option>
                                <option
                                    <?php if (isset($params['order']) && $params['order'] == 'number_of_products'): ?>selected="selected"<?php endif; ?>
                                    value="<?php echo $this->getUrl() . $urlKey . '?' . $query . '&dir=asc' . '&order=number_of_products'; ?>">
                                        <?php echo $this->__('Number of Products'); ?>
                                </option>
                            </select>
                        <?php else: ?>
                            <select onchange="setLocation(this.value)">
                                <option
                                    <?php if (isset($params['order']) && $params['order'] == 'priority'): ?>selected="selected"<?php endif; ?>
                                    value="<?php echo $this->getUrl() . $urlKey . '?' . $query . '&dir=' . $params['dir'] . '&order=priority'; ?>">
                                        <?php echo $this->__('Priority'); ?>
                                </option>
                                <option
                                    <?php if (isset($params['order']) && $params['order'] == 'title'): ?>selected="selected"<?php endif; ?>
                                    value="<?php echo $this->getUrl() . $urlKey . '?' . $query . '&dir=' . $params['dir'] . '&order=title'; ?>">
                                        <?php echo $this->__('Title'); ?>
                                </option>
                                <option
                                    <?php if (isset($params['order']) && $params['order'] == 'number_of_products'): ?>selected="selected"<?php endif; ?>
                                    value="<?php echo $this->getUrl() . $urlKey . '?' . $query . '&dir=' . $params['dir'] . '&order=number_of_products'; ?>">
                                        <?php echo $this->__('Number of Products'); ?>
                                </option>
                            </select>
                        <?php endif; ?>
                        <?php if (!isset($params['order'])): ?>
							<?php if (isset($params['dir']) && $params['dir'] != 'desc'): ?>
								<a title="Set Descending" href="<?php echo $this->getUrl() . $urlKey . '?' . $query . '&dir=desc&order=priority'; ?>"><i class="fa fa-arrow-down"></i></a>
                            <?php else: ?>
								<a title="Set Ascending" href="<?php echo $this->getUrl() . $urlKey . '?' . $query . '&dir=asc&order=priority'; ?>"><i class="fa fa-arrow-up"></i></a>
							<?php endif ?>
                        <?php else: ?>
							<?php if (isset($params['dir']) && $params['dir'] != 'desc'): ?>
								<a title="Set Descending" href="<?php echo $this->getUrl() . $urlKey . '?' . $query . '&dir=desc&order=' . $params['order']; ?>"><i class="fa fa-arrow-down"></i></a>
                            <?php else: ?>
								<a title="Set Ascending" href="<?php echo $this->getUrl() . $urlKey . '?' . $query . '&dir=asc&order=' . $params['order']; ?>"><i class="fa fa-arrow-up"></i></a>
							<?php endif ?>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php if (!isset($params['dir'])): ?>
                            <select onchange="setLocation(this.value)">
                                <option
                                    <?php if (isset($params['order']) && $params['order'] == 'priority'): ?>selected="selected"<?php endif; ?>
                                    value="<?php echo $this->getUrl() . $urlKey . '?' . 'dir=asc' . '&order=priority'; ?>">
                                        <?php echo $this->__('Priority'); ?>
                                </option>
                                <option
                                    <?php if (isset($params['order']) && $params['order'] == 'title'): ?>selected="selected"<?php endif; ?>
                                    value="<?php echo $this->getUrl() . $urlKey . '?' . 'dir=asc' . '&order=title'; ?>">
                                        <?php echo $this->__('Title'); ?>
                                </option>
                                <option
                                    <?php if (isset($params['order']) && $params['order'] == 'number_of_products'): ?>selected="selected"<?php endif; ?>
                                    value="<?php echo $this->getUrl() . $urlKey . '?' . 'dir=asc' . '&order=number_of_products'; ?>">
                                        <?php echo $this->__('Number of Products'); ?>
                                </option>
                            </select>
                        <?php else: ?>
                            <select onchange="setLocation(this.value)">
                                <option
                                    <?php if (isset($params['order']) && $params['order'] == 'priority'): ?>selected="selected"<?php endif; ?>
                                    value="<?php echo $this->getUrl() . $urlKey . '?' . 'dir=' . $params['dir'] . '&order=priority'; ?>">
                                        <?php echo $this->__('Priority'); ?>
                                </option>
                                <option
                                    <?php if (isset($params['order']) && $params['order'] == 'title'): ?>selected="selected"<?php endif; ?>
                                    value="<?php echo $this->getUrl() . $urlKey . '?' . 'dir=' . $params['dir'] . '&order=title'; ?>">
                                        <?php echo $this->__('Title'); ?>
                                </option>
                                <option
                                    <?php if (isset($params['order']) && $params['order'] == 'number_of_products'): ?>selected="selected"<?php endif; ?>
                                    value="<?php echo $this->getUrl() . $urlKey . '?' . 'dir=' . $params['dir'] . '&order=number_of_products'; ?>">
                                        <?php echo $this->__('Number of Products'); ?>
                                </option>
                            </select>
                        <?php endif; ?>
                        <?php if (!isset($params['order'])): ?>
							<?php if (isset($params['dir']) && $params['dir'] != 'desc'): ?>
								<a title="Set Descending" href="<?php echo $this->getUrl() . $urlKey . '?' . 'dir=desc&order=priority'; ?>"><i class="fa fa-arrow-down"></i></a>
                            <?php else: ?>
								<a title="Set Ascending" href="<?php echo $this->getUrl() . $urlKey . '?' . 'dir=asc&order=priority'; ?>"><i class="fa fa-arrow-up"></i></a>
							<?php endif ?>
                        <?php else: ?>
							<?php if (isset($params['dir']) && $params['dir'] != 'desc'): ?>
								<a title="Set Descending" href="<?php echo $this->getUrl() . $urlKey . '?' . 'dir=desc&order=' . $params['order']; ?>"><i class="fa fa-arrow-down"></i></a>
                            <?php else: ?>
								<a title="Set Ascending" href="<?php echo $this->getUrl() . $urlKey . '?' . 'dir=asc&order=' . $params['order']; ?>"><i class="fa fa-arrow-up"></i></a>
							<?php endif ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <ul class="feature-brands row-5">
			<?php $i = 0 ?>
            <?php foreach ($collection as $brand): ?>
				<?php $i++ ?>
                <li class="feature-brand-item col-md-3 col-sm-4 col-xs-6 <?php if ($i % 4 == 1): ?>first-row-item <?php endif; ?> <?php if ($i % 2 == 1): ?>row-2-first<?php endif; ?> <?php if ($i % 3 == 1): ?>row-3sm-first<?php endif; ?>">
                    <div class="feature-brand-image">
                        <a title="<?php echo $brand->getTitle(); ?>"
                           href="<?php echo $this->getUrl() . $urlKey . '/' . $brand->getUrlKey(); ?>">
                               <?php if ($brand->getIcon() != ''): ?>
                                <img style="width: <?php echo $iconWidth ?>px;" class="brand-img img-responsive" alt="<?php echo $brand->getTitle(); ?>"
                                     src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'media/' . $brand->getIcon(); ?>">
                                 <?php else: ?>
                                <img style="width: <?php echo $iconWidth ?>px;" class="brand-img img-responsive" alt="<?php echo $brand->getTitle(); ?>"
                                     src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'media/mgs/brand/no_image.jpg'; ?>">
                                 <?php endif; ?>
                        </a>
                    </div>
                    <h3 class="feature-brand-title">
                        <a title="<?php echo $brand->getTitle(); ?>"
                           href="<?php echo $this->getUrl() . $urlKey . '/' . $brand->getUrlKey(); ?>"><?php echo $brand->getTitle(); ?>
                            <span><?php echo $this->__('(%s)', $this->getProductCount($brand->getId())); ?></span></a>
                    </h3>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <div class="brand-mgs">
            <p class="note-msg"><?php echo $this->__('There are no brands matching the selection.'); ?></p>
        </div>
    <?php endif; ?>
</div> 
