<?php
/* * ****************************************************
 * Package   : Brand
 * Author    : HIEPNH
 * Copyright : (c) 2015
 * ***************************************************** */
?>
<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$model = $this->getBrand();
$helper = Mage::helper('brand');
?>
<?php $panelHelper = $this->helper('mpanel') ?>
<?php $size = $panelHelper->convertRatioToSize($this->getProductRatio()) ?>
<?php $perrow = $panelHelper->getPerrow(); ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if ($model->getImage() != ''): ?>
    <p class="category-image">
        <img class="img-responsive"
             title="<?php echo $model->getTitle(); ?>" alt="<?php echo $model->getTitle(); ?>"
             src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'media/' . $model->getImage(); ?>">
    </p>
<?php endif; ?>

<?php if ($model->getDescription() != ''): ?>
    <div class="category-description std">
        <p><?php echo $model->getDescription(); ?></p>
    </div>
<?php endif; ?>

<?php if (!$_productCollection->count()): ?>
	<div class="alert alert-warning"><?php echo $this->__('There are no products matching the selection.') ?></div>
<?php else: ?>
    <div class="category-products">
		<div class="top-deals-toolbar">
			<?php echo $this->getToolbarHtml() ?>
		</div>
        <?php // List mode ?>
        <?php if ($this->getMode() != 'grid'): ?>
            <?php $_iterator = 0; ?>
			<div class="category-content">
            <div class="products-list" id="products-list">
                <?php foreach ($_productCollection as $_product): ?>
                    <div class="row item<?php if (++$_iterator == sizeof($_productCollection)): ?> last<?php endif; ?>">
						<div class="col-md-3 col-sm-6 col-xs-12">
							<a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                           class="product-image"><img class="img-responsive"
                                src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']); ?>"
                                alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></a>
						</div>
						<div class="product-content col-md-9 col-sm-6 col-xs-12">
							<div class="f-fix">
								<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
								<h2 class="product-name">
									<a href="<?php echo $_product->getProductUrl() ?>"
                                    title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                                </h2>
								<?php echo $this->getReviewsSummaryHtml($_product) ?>
								<?php echo $this->getPriceHtml($_product, true) ?>
								<div class="controls-list">
									<ul class="icon-links">
										<?php if ($_product->isSaleable()): ?>
											<li><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="fa fa-shopping-cart"></i><?php echo $this->__('Add to Cart') ?></button></li>
										<?php endif; ?>
										<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
											<li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-search"></em></button></li>
										<?php endif ?>
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="fa fa-heart-o"></em></button></li>
										<?php endif; ?>
										<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
											<li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-retweet"></em></button></li>
										<?php endif; ?>
									</ul>
								</div>
								<div class="desc std">
                                    <p><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>
                                    <a href="<?php echo $_product->getProductUrl() ?>"
                                       title="<?php echo $_productNameStripped ?>"
                                       class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>
							</div>
						</div>
                    </div>
                <?php endforeach; ?>
            </div>
			</div>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php else: ?>

            <?php // Grid Mode ?>
		<div class="products-grid row-<?php echo $perrow ?>">
			<div class="row">
            <?php $_collectionSize = $_productCollection->count() ?>
            <?php $_columnCount = $this->getColumnCount(); ?>
			<?php $col = $panelHelper->getCol() ?>
            <?php
            $i = 0;
            foreach ($_productCollection as $_product):
                ?>
				<?php $i++; ?>
				<?php $class = $panelHelper->getItemClass($perrow, $i) ?>
                    <div class="item col-md-<?php echo $col ?> col-sm-6 col-xs-12 <?php if ($i % $perrow == 1): ?>first-row-item<?php endif; ?><?php echo $class ?>">
                        <div class="product-content">
							<div class="product-top">						
								<a href="<?php echo $_product->getProductUrl() ?>"
								title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
								class="product-image">
								<img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']); ?>"
                                alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
								<img class="img-responsive img-two" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($size['width'], $size['height']); ?>"
                                alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'image'), null, true) ?>"/></a>
								<div class="controls">
									<div class="add-to-cart">
										<?php if ($_product->isSaleable()): ?>
											<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart btn btn-default btn-xs"
													onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
												<span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
										<?php else: ?>
											<button disabled type="button" title="<?php echo $this->__('Out of stock') ?>" class="btn-cart btn btn-default btn-xs">
												<span><span><?php echo $this->__('Out of stock') ?></span></span></button>
											<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
										<?php endif; ?>
									</div>
									<ul class="icon-links pull-right">									
										<?php if ($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
											<li class="li-quickview">
												<button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" 
												onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-search"></em></button>
											</li>
										<?php endif ?>
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="fa fa-heart-o"></em></button></li>
										<?php endif; ?>
										<?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
											<li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-retweet"></em></button></li>
										<?php endif; ?>
									</ul>
								</div>
							</div>
							<div class="product-desc">
								<h4 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                    title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
								</h4>
								<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
								
                                <?php echo $this->getPriceHtml($_product, true) ?>
							</div>
						</div>
                    </div>
            <?php endforeach ?>
			</div>
		</div>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>
        <?php endif; ?>

        <div class="bottom-toolbar">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>
<?php endif; ?>